function IMSES
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   (C) Copyright by Siemens Schweiz AG, Building Technologies Group,
%       HVAC Products, 2012
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   Project                     : IMSES
%   Target Hardware             : PC 
%   Target Operating System     : WinXP Console
%   Language/Compiler           : Matlab 2010 and higher 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   Workfile                    : GUI.m
%   Author                      : Thomas Rohr
%   Version                     : v1.1
%   Date                        : 20-Feb-2012
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Matlab Informations
% GUI.m:
%   Ensure you have successfully downloaded the "FindJObj" function 
%   from MATLAB File Exchange:
%   http://www.mathworks.com/matlabcentral/fileexchange/14317
%   FindJObj - is a utility programmed by Yair Altman used to access 
%   the underlying Java components to enable customizations that are 
%   unavailable in standard Matlab.
%   For more information visit: http://undocumentedmatlab.com/
% ImportXML.m
%   Ensure you have successfully downloaded the "XMl2STRUCT" function 
%   from MATLAB File Exchange:
%   http://www.mathworks.com/matlabcentral/fileexchange/28518-xml2struct
% ImportBA_XML.m
%   There is a Problem with XpathFactory in Matlab 2010 and maybe higher
%   Versions. You have to disable a static java path. Open the File:
%   ..\MATLAB\R2010bSP1\toolbox\local\classpath.txt
%   and set the following line in comment, like shown below. 
%   ## $matlabroot/java/jarext/saxon9-xpath.jar
%
%   The BACNet Importer uses the new Matlab option of 
%   (OOP) Object Oriented Programming in Matlab which is available since 
%   Matlab 2008 it will not work with previous Versions.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Description:
%   GUI - graphical user interface to manage the following functionalities:
% * Import programm information from XML-Files generated by the 
%   Siemens TIA Portal to Simulink
% * Export programm information from Simulink to XML-Files that can be
%   imported to the Siemens TIA Portal
% * SCL2C - Manage the automated translation prozess from SCL to C
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Necessary Files:
%   * Current version of the Firmware Library (example: ApplFwS1v1_LIB.mdl)
%   * Callback.m
%   * xml2struct.m
%   * findjobj.m
%   * getapplicationdatadir.m
%   * All attendant functions,subfuctions and class files
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Function/Interface:
%	  
%   function GUI
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%  Revision History 
% 	(Put meaningful comments in SourceSafe for log below!)
% 	(Please remove blank lines and very old comments!)
% 	
% 	2012-03-20 14:00 Thomas Rohr
%	Header comment was attached
% 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% 1. necessary paths
IMSESPath = which ('IMSES');
IMSESPath = strrep(IMSESPath, 'IMSES.m', '');

addpath(genpath(IMSESPath)); % add IMSESPath with all subfolders
SFunPath=strrep (IMSESPath,'Tools\IMSES_Gui\','bin');
addpath(SFunPath); %add Path to S-Functions (not needed for import,...
                   %but needed for simulation

%% Initialisation
% pwd returns the current matlab folder
% these variables store the path selected by the browse button
h.ImportPathName=pwd;
h.ImportChartPathName=pwd;
h.ExportPathName=pwd;
h.LibFilePathName=pwd;
h.MatlabPathName=pwd;
scl_list = 0;
build_list = 0;
% Initialisation of the Filterindex for the Import Browse Button
h.ImportBrowseFilterIndex=1;
h.ImpBrwsLastSel='*.zip';
h.ImpBrwsLastSelStr=['Full Import (' h.ImpBrwsLastSel ')'];
%% Log File
LogFilePath = getapplicationdatadir('CFC2SL', true, true);
h.LogFileLocal = [LogFilePath '\' 'CFC2SL_LogFile.xml'];
% if not exists CFC2SL_LogFile
if ~(exist([LogFilePath '\' 'CFC2SL_LogFile.xml']) == 2)
    % copy CFC2SL_LogFile to APPDATA Path
    [status,message,messageId]=copyfile(...
        [IMSESPath '\Lib\LogFile\CFC2SL_LogFile.xml'], ...
        [LogFilePath '\' 'CFC2SL_LogFile.xml']);
end
%delete the fileattrib 'w' for write access
if (exist([LogFilePath '\' 'CFC2SL_LogFile.xml']) == 2)
    [status, message, messageid] = fileattrib(...
        [LogFilePath '\' 'CFC2SL_LogFile.xml'],'+w');
end

% creating a document object model node of the XML File
h.xDocLogFile = xmlread(h.LogFileLocal);
% XPath Factory
import javax.xml.xpath.*
factory = XPathFactory.newInstance;
xpath = factory.newXPath;
%% Firmware Library
% finding the FirmwareLib Node
expr=xpath.compile('.//FirmwareLib');
FirmwareLibNode=expr.evaluate(h.xDocLogFile, XPathConstants.NODE);
FirmwareLib=FirmwareLibNode.getAttribute('Value');
FirmwareLib=char(FirmwareLib);
% if the Value of FirmwarLib is empty
if isempty(FirmwareLib)
    ConfigLibWarn=msgbox({'The Library File is not Configured yet.';...
        'Please select the Library File'},...
        'Configure Library File','warn');
    % select the Firmware Library File
    [FileName,PathName,FilterIndex] = uigetfile( ...
                    {'*.mdl','Library-File (*.mdl)'; ...
                    '*.*',  'All Files (*.*)'}, ...
                    'Select Library-File',h.LibFilePathName);
    FirmwareLib = [PathName FileName];  
    if FileName > 0 
        try
        % close the Message Box if not already closed
        close(ConfigLibWarn);
        catch
        end
        % save the Path in guidata for the next invoke of uigetfile 
        h.LibFilePathName = PathName;
        % change the Attribute 
        FirmwareLibNode.setAttribute('Value',FirmwareLib)
        % writing the DOM xDocLogFile to the XML-File LogFileLocal
        %xmlwrite(h.LogFileLocal,result); % This is not working
        % It creates extra whitespace after every call
        % This is a workaround to solve the whitespace problem
        %LogFile as string
        LogFileStr = xmlwrite(h.xDocLogFile);
        %remove extra tabs, spaces and extra lines
        LogFileStr = regexprep(LogFileStr,'\n[ \t\n]*\n','\n'); 
        %Write to file
        LogFilehandle = fopen(h.LogFileLocal,'w');
        fprintf(LogFilehandle,'%s\n',LogFileStr);
        fclose(LogFilehandle);
    else
        msgbox(...
        '    ERROR : No File was selected',...
        'No File was selected','error');
        return
    end
end
% reading the Firmwarelibrary again
expr=xpath.compile('.//FirmwareLib/@Value');
result=expr.evaluate(h.xDocLogFile, XPathConstants.STRING);
FirmwareLib = result;
h.LibFile = FirmwareLib;
[FirmwareLibPath,~,~]=fileparts(FirmwareLib);
if ~exist(FirmwareLibPath)
   msgbox(...
       {'    ERROR : Firmware Library Path could not be located.';...
        '    * Check if Clear Case is working';...
        '    * Check if the defined Firmeware Library is available';...
        '    * The Log File will be deleted'},...
        'Firmware Library Path does not exist','error');
    delete(h.LogFileLocal);
    return
end
addpath(FirmwareLibPath);
% saving the FirmwareLibPath for the set Lib Button
h.LibFilePathName = [FirmwareLibPath '\'];
%% Figure
% building a window without tool- and menubar
h.fig = figure('NumberTitle','off',...              % delete figure name
                    'Name','IMSES',...              % new figure name 
                    'MenuBar','none',...            % delete menubar
                    'ToolBar','none',...            % delete toolbar
                    'Resize','off',...              % disable resizing
                    'Pos',[400 50 750 600]);       % position and size
%% Tab
% Warning: The uitabgroup object is undocumented and some of 
% its properties will become obsolete in a future release.
% Warning Control:
warning('off', 'MATLAB:uitabgroup:OldVersion');
%warning('on', 'MATLAB:uitabgroup:OldVersion');

h.TabGroup = uitabgroup; 
h.tab1 = uitab(h.TabGroup, 'title','Import');
h.tab2 = uitab(h.TabGroup, 'title','Export');
h.tab3 = uitab(h.TabGroup, 'title','SCL2C');
h.tab4 = uitab(h.TabGroup, 'title','Info/Settings');
%% Background Image
backgroundImage = imread([IMSESPath 'Lib/Logo/SIEMENS.tif']);
%select the axes
h.axes1=axes('unit','pix','pos',[630 0 120 29]);
%place image onto the axes
image(backgroundImage);
%remove the axis tick marks
axis off
%% Menu
h.FileMenu = uimenu('Parent',h.fig,...
                    'HandleVisibility','callback', ...
                    'Label','File');
h.OpenMenuitem = uimenu('Parent',h.FileMenu,...
                    'Label','Open',...
                    'HandleVisibility','callback', ...
                    'Callback', @hOpenMenuitemCallback);
h.ImportMenuitem = uimenu('Parent',h.FileMenu,...
                    'Label','Import',...
                    'HandleVisibility','callback', ...
                    'Callback', @hOpenMenuitemCallback);
h.ExportMenuitem = uimenu('Parent',h.FileMenu,...
                    'Label','Export',...
                    'HandleVisibility','callback', ...
                    'Callback', @hOpenMenuitemCallback);                    
h.CloseMenuitem = uimenu('Parent',h.FileMenu,...
                    'Label','Close',...
                    'Separator','on',...
                    'HandleVisibility','callback', ...
                    'Callback', @hCloseMenuitemCallback);
h.HelpMenu = uimenu('Parent',h.fig,...
                    'HandleVisibility','callback', ...
                    'Label','Help');                    
%% Toolbar
h.Toolbar = uitoolbar(...    % Toolbar for Open and Print buttons
                   'Parent',h.fig, ...
                   'HandleVisibility','callback');
% hOpenPushtool  =  uipushtool(...   % Open toolbar button
%                    'Parent',hToolbar,...
%                    'TooltipString','Open File',...
%                    'CData',iconRead(fullfile(matlabroot,...
%                        'toolbox\matlab\icons\opendoc.mat')),...
%                    'HandleVisibility','callback', ...
%                    'ClickedCallback', @hOpenMenuitemCallback);
% hPrintPushtool = uipushtool(...    % Print toolbar button
%                     'Parent',hToolbar,...
%                     'TooltipString','Print Figure',...
%                     'CData',iconRead(fullfile(matlabroot,...
%                         'toolbox\matlab\icons\printdoc.mat')),...
%                     'HandleVisibility','callback', ...
%                     'ClickedCallback', @hPrintMenuitemCallback);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Tab 1 Import
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Import Panel
h.panel_1_1 = uipanel(h.tab1,...
                    'Title','Import',...
                    'unit','pix',...
                    'Position',[5 435 740 130]);
% Path editbox
h.edit_1_1 = uicontrol('Parent',h.panel_1_1,...
                    'style','edit',...
                    'unit','pix',...
                    'BackgroundColor','white',...
                    'HorizontalAlignment','left',...
                    'Position',[20 70 690 25]);
% Browse Button
h.button_1_1 = uicontrol('Parent',h.panel_1_1,...
                    'Style','pushbutton',...
                    'String','Browse ...',...
                    'Position',[20 20 80 25],...
                    'Callback',@pushbutton_1_1_Callback);
% % change the Cursor to Hand Cursor when location is over the button                
% j.button_1_1 = findjobj(h.button_1_1);
% j.button_1_1.setCursor(java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

% Start Button
h.button_1_2 = uicontrol('Parent',h.panel_1_1,...
                    'Style','pushbutton',...
                    'String','Start',...
                    'Position',[630 20 80 25],...
                    'Callback',@pushbutton_1_2_Callback);
% % change the Cursor to Hand Cursor when location is over the button
% j.button_1_2 = findjobj(h.button_1_2);
% j.button_1_2.setCursor(java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

% UnZip Button
h.button_1_4 = uicontrol('Parent',h.panel_1_1,...
                    'Style','pushbutton',...
                    'String','UnZip',...
                    'Position',[105 20 80 25],...
                    'Callback',@pushbutton_1_4_Callback);
% % change the Cursor to Hand Cursor when location is over the button                
% j.button_1_4 = findjobj(h.button_1_4);
% j.button_1_4.setCursor(java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));         

% Open Folder Button
h.button_1_5 = uicontrol('Parent',h.panel_1_1,...
                    'Style','pushbutton',...
                    'String','Open Folder',...
                    'Position',[190 20 80 25],...
                    'Callback',@pushbutton_1_5_Callback);
                
% Akctivate Dissolve Algebraic Loop                
h.cheackbox_1_1 = uicontrol('Parent',h.panel_1_1, ...
                        'Style','checkbox',...
                        'String', 'Dissolve Algebraic Loop',...
                        'Value', 1, 'Position',[480 20 140 20]);
                
% % change the Cursor to Hand Cursor when location is over the button                
% j.button_1_5 = findjobj(h.button_1_5);
% j.button_1_5.setCursor(java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));         
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Status - Panel
h.panel_1_2 = uipanel(h.tab1,...
                    'Title','Status',...
                    'unit','pix',...
                    'Position',[5 40 740 395]);
% Status - Textbox
h.edit_1_2 = uicontrol('Parent',h.panel_1_2,...   
                    'style','edit',...
                    'unit','pix',...
                    'Max',2,...
                    'BackgroundColor','white',...
                    'HorizontalAlignment','left',...
                    'Position',[20 70 690 290]);
% get Java handle
j.edit_1_2 = findjobj(h.edit_1_2);
% bei gelegenheit noch ein workaround schreiben
% die funktion findjobj legt das java handle teilweise in ein array
j.editbox_1=j.edit_1_2.getViewport().getComponent(0);

% set edit-box to read-only
j.editbox_1.setEditable(false);
% turn off word-wrapping
j.editbox_1.setWrapping(false);
% enable horizontal scrolling
set(j.edit_1_2,'HorizontalScrollBarPolicy',30);

% Print to Matlab - Button
h.button_1_3 = uicontrol('Parent',h.panel_1_2,...
                    'style','push',...
                    'unit','pix',...
                    'position',[20 20 80 25],...
                    'string','Print to File');
set(h.button_1_3,'callback',@pushbutton_1_3_Callback) % Set callbacks.
% change the Cursor to Hand Cursor when location is over the button                
j.button_1_3 = findjobj(h.button_1_3);
j.button_1_3.setCursor(java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));   

% Save the handle structure (h)
MainFigure = h.fig;
guidata(MainFigure,h);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Tab 1 Callback Functions                
function pushbutton_1_1_Callback(hObject, eventdata)
% hObject    handle to pushbutton1 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
    % Load the handle structure (h) 
    h = guidata(hObject);
    % selecting the status box Handle
    h.status = h.edit_1_2;
    % switch FilterIndex of the previous invocation
    switch h.ImportBrowseFilterIndex
        case 1
            % do nothing
        case 2
            h.ImpBrwsLastSel='*.zip';
            h.ImpBrwsLastSelStr=['Full Import (' h.ImpBrwsLastSel ')'];
        case 3
            h.ImpBrwsLastSel='*.ba';
            h.ImpBrwsLastSelStr=['Single BA-Chart Import (' h.ImpBrwsLastSel ')'];
        case 4
            h.ImpBrwsLastSel='*.xml';
            h.ImpBrwsLastSelStr=['Single Chart Import (' h.ImpBrwsLastSel ')'];
        case 5
            h.ImpBrwsLastSel='*.xml;*.ba';
            h.ImpBrwsLastSelStr=['Multi Import (' h.ImpBrwsLastSel ')'];
        otherwise
            h.ImpBrwsLastSel='*.zip';
            h.ImpBrwsLastSelStr=['Full Import (' h.ImpBrwsLastSel ')'];
    end
   
    % Open the file selection pop up
    [FileName,PathName,FilterIndex] = uigetfile( ...
        {h.ImpBrwsLastSel, ['Last Selection: ' h.ImpBrwsLastSelStr ];...
        '*.zip','Full Import (*.zip)'; ...
        '*.ba','Single BA-Chart Import (*.ba)'; ...
        '*.xml','Single Chart Import (*.xml)'; ...
        '*.xml;*.ba','Multi Import (*.xml;*.ba)'; ...
        '*.*',  'All Files (*.*)'}, ... % Filterdefinition
        'Select Import-File',... % Headline
        'MultiSelect', 'on',... % Property MultiSelect (on/off)
        h.ImportPathName); % PathName of the previous invocation
        
    % proof if one ore more files have been selected            
    if iscell(FileName)
        % more than one file
        TempString = [PathName FileName{1}];
        for k=2:length(FileName)
            if FileName{k}>0
                TempString=[TempString ';' FileName{k}];
            end
        end
        set(h.edit_1_1, 'String', TempString);
    else
        % zero or one file
        if FileName>0
            set(h.edit_1_1, 'String', [PathName FileName]);
        end          
    end
    if PathName>0
    % save the FilterIndex for the next invoke of uigetfile                
    h.ImportBrowseFilterIndex=FilterIndex;    
    % save the Path in guidata for the next invoke of uigetfile
    h.ImportPathName = PathName;
    end
    % Update the handle structure (h)
    guidata(hObject,h);
 end    
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function pushbutton_1_2_Callback(hObject, eventdata)
% hObject    handle to pushbutton2 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
    % set a default value for BaObjRef.DeviceId
    BaObjRef.DeviceId = 0;
    % Load the handle structure (h) 
    h = guidata(hObject);
    % Writing to Status Textbox
    set(h.edit_1_2, 'String', {[' === Status Report (' datestr(now) ') ===']; ''})
    % Get the selected file 
    File_Selected=get(h.edit_1_1,'String');
    % Split the String
    File_Selected=regexp(File_Selected,';','split');
%% classification of the import case
    % initialisation
    BACounter = 0;
    Errors = 0;
    %detect if its one or more files
    if length(File_Selected)==1
        % single File
        MulitFile = false;
        % Get the file extension
        File_Selected=File_Selected{1};
        [pathstr, name, ext] = fileparts(File_Selected);
    elseif length(File_Selected)>1
        % multi File
        % seperate the FilePath from the List
        [pathstr, name, ext] = fileparts(File_Selected{1});
        MultiFilePath=pathstr;
        File_Selected{1}=[name ext];
      % -> File_Selected contains only Files at this stage
        % proof if more than one *.ba File is in the list
        % if *.ba File > 1 send a message to correct the input
        TempLength=length(File_Selected);
        TempIndex = 1;
        for k=1:TempLength
            [~,~,ext]=fileparts(File_Selected{TempIndex});
            % seperate the *.ba File if one is existing

            if strcmp(ext,'.ba')
                if BACounter > 0
                    % Writing to Status Textbox
                    Send2GUI(...
                    {'    ERROR : Too many *.ba Files inside the Input String';...
                     '    * Correct the Input'}...
                     ,h.status);
                    % Messagebox (Error)
                    msgbox(...
                        {'Too many *.ba Files inside the Input String';...
                         '-> Correct the Input'},...
                         'Error: Too many *.ba Files','error');
                    break
                end
                % seperate the *.ba File
                BAFile=File_Selected{TempIndex};
                % delete the possition in the array
                File_Selected(TempIndex) = [];
                % decrement the temp array length
                TempLength=TempLength-1;
                % decrement the index variable
                TempIndex=TempIndex-1;
                % increment the *.ba File counter
                BACounter=BACounter+1;
            end
            if ~(strcmp(ext,'.xml') || strcmp(ext,'.ba'))
                File_Selected(TempIndex)=[];
                % decrement the temp array length
                TempLength=TempLength-1;
                % decrement the index variable
                TempIndex=TempIndex-1;
            end
          % -> File_Selected contains only *.xml Files at this stage
          % increment the index variable after the iteration
          TempIndex=TempIndex+1;
        end
        %classify the import case
        if BACounter == 0
            ext='.xml';
            MulitFile = true;
        elseif BACounter == 1
            ext='.ba';
            MulitFile = true;
        end
    end  
%% select import case
%%% Full Import (*.zip)
    if strcmp(ext,'.zip') && (MulitFile == false )
        if exist([pathstr '\_TEMP_UNZIP_FOLDER']) == 7
        % delete directory if it already exists
        % (when the GUI executes with error the Folder can not be deleted, so it needs to be proofed here)
        rmdir([pathstr '\_TEMP_UNZIP_FOLDER'],'s')
        end
        unzip(File_Selected,[pathstr '\_TEMP_UNZIP_FOLDER']);
        BA_FILE = dir([pathstr '\_TEMP_UNZIP_FOLDER\*.ba']);
        if numel(BA_FILE) == 1 
            % Import des .ba Files
             [Errors,BaObjRef.DeviceId,MdlFilePath]=ImportBA_XML([pathstr '\_TEMP_UNZIP_FOLDER\' BA_FILE(1).name],h,FirmwareLib);
             % Wiederholen des Aufrufs wenn  Errormeldung = 2 (Überschreiben) 
             if Errors == 2
                 % Writing to Status Textbox
                 set(h.edit_1_2, 'String', {[' === Status Report (' datestr(now) ') ===']; ''})
                 [Errors,BaObjRef.DeviceId,MdlFilePath]=ImportBA_XML([pathstr '\_TEMP_UNZIP_FOLDER\' BA_FILE(1).name],h,FirmwareLib);
             end
        end
        CHART_FILES = dir([pathstr '\_TEMP_UNZIP_FOLDER\*.xml']);
        if (numel(CHART_FILES) > 0) && (Errors == 0)
        % Import der Chart Files 
            for i=1:numel(CHART_FILES)
               [in out err] = ImportXML([pathstr '\_TEMP_UNZIP_FOLDER\' CHART_FILES(i).name],MdlFilePath,BaObjRef,h,FirmwareLib);
               xmlChart = [pathstr '\_TEMP_UNZIP_FOLDER\' CHART_FILES(i).name];
            end
        end
        rmdir([pathstr '\_TEMP_UNZIP_FOLDER'],'s')
    end

%%% BA-Chart Import (*.ba)
    if strcmp(ext,'.ba') 
        if (MulitFile == true )
            BAFile = [MultiFilePath '\' BAFile];
            % change the extension for the following chart import
            ext = '.xml';
        elseif (MulitFile == false )
            BAFile = File_Selected;
        end
        [Errors,BaObjRef.DeviceId,MdlFilePath]=ImportBA_XML(BAFile,h,FirmwareLib);
        % Wiederholen des Aufrufs wenn  Errormeldung = 2 (Überschreiben) 
        if Errors == 2
          % Writing to Status Textbox
          set(h.edit_1_2, 'String', {[' === Status Report (' datestr(now) ') ===']; ''});
          [Errors,BaObjRef.DeviceId,MdlFilePath]=ImportBA_XML(BAFile,h,FirmwareLib);
        end  
    end       

%%% Chart Import (*.xml)
    if strcmp(ext,'.xml')
        % if no BACNet File is existing
        if (BACounter == 0)

         FileConsistentHint=msgbox(...
         {'The *.xml File you want to Import needs to fit to the selected *.mdl File.';...
          'Example: The File "Chart_R_1''CcgRad01@RTPrt01.xml" belongs to an R_1.mdl File'},...
        'File Consistent','warn');       
        % Open the file selection pop up
        [~,ModelFilePath,FilterIndex] = uigetfile( ...
                    {'*.mdl','Simulink Model (*.mdl)'; ...
                    '*.*',  'All Files (*.*)'}, ... % Filterdefinition
                    'Select Mdl-File',...  % Headline
                    h.ImportChartPathName); % PathName of the previous invocation
        if FilterIndex == 0
            return % Cancel if no Path was selected
        end
        try
            % close the message box again
            close(FileConsistentHint);
        catch
        end
        % save the Path in guidata for the next invoke of uigetfile
        h.ImportChartPathName = ModelFilePath; 
        % if BACNet File is existing 
        elseif (BACounter == 1)
            ModelFilePath = MdlFilePath;
        end
        if (MulitFile == false )
            [FilePath, name, ~] = fileparts(File_Selected);
            CHART_FILES{1}= name;
        elseif (MulitFile == true )
            FilePath = MultiFilePath;
            CHART_FILES = File_Selected;
        end
        
        if (numel(CHART_FILES) > 0) && (Errors == 0)
        % Import der Chart Files 
            for i=1:numel(CHART_FILES)
               [in out err] = ImportXML([FilePath '\' CHART_FILES{i}],ModelFilePath,BaObjRef,h,FirmwareLib);
            end
        end
    end

%%% Error Message   
    if ~(strcmp(ext,'.zip') || strcmp(ext,'.ba')  || strcmp(ext,'.xml'))
        msgbox('Permitted File Extensions: (*.zip ; *.ba ; *.xml)',...
                    'Error: Wrong File Extension','error');
    end
    % Update the handle structure (h)
    guidata(hObject,h);
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [] = pushbutton_1_3_Callback(hObject, eventdata)
    % callback for pushbutton
    
    % Load the handle structure (h)
    h = guidata(hObject);
    % get the Status String
    Text = get(h.edit_1_2,'string');
    % search for the File-Path in the Status String
    RegExp = regexp(Text,'<(.*)>','tokens','once');
    % get the Index of the first not empty field
    Index = find(not(cellfun('isempty', RegExp)),1,'first');
    % form the File-Path
    FilePath=[RegExp{Index}{1,1}];
    % delete the last position (example: 'R_2/BA/Rad01/Rad01' --> 'R_2/BA/Rad01')
    FilePath = FilePath(1:find(FilePath=='\',1,'last')-1);
    % delete one more position if the file comes from a UNZIP-Folder
    if  ~isempty(strfind(FilePath,'\_TEMP_UNZIP_FOLDER'))
        FilePath = FilePath(1:find(FilePath=='\',1,'last')-1);
    end
    % search for the Model Name in the Status String
    % searching for the string between 'to  ' and '.mdl'
    RegExp = regexp(Text,'to\s+(.*).mdl','tokens','once');
    % get the Index of the first not empty field
    Index = find(not(cellfun('isempty', RegExp)),1,'first');
    % 
    ModelName=RegExp{Index}{1,1};
    
    FilePath= [FilePath '\' ModelName];
    % create the text file
    FileName=[FilePath '\' datestr(now, 'yy-mm-dd_-_HH-MM') '_IMPORT_STATUS.txt'];
    file = fopen(FileName,'w');
    %
    for i=1:length(Text)
        fprintf(file,'%s\n',Text{i});
    end
    fclose(file);
    open(FileName);
    % Update the handle structure (h)
    guidata(hObject,h);
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function pushbutton_1_4_Callback(hObject, eventdata)
% hObject    handle to pushbutton1 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
    % Load the handle structure (h) 
    h = guidata(hObject);
    % Get the selected file 
    File_Selected=get(h.edit_1_1,'String');
    % Get the file extension
    [pathstr, name, ext] = fileparts(File_Selected);
    if strcmp(ext,'.zip')
        if exist([pathstr '\' name]) == 7
        % delete directory if it already exists
        % (when the GUI executes with error the Folder can not be deleted, so it needs to be proofed here)
        rmdir([pathstr '\' name],'s')
        end 
        unzip(File_Selected,[pathstr '\' name]);       
    end
    % Update the handle structure (h)
    guidata(hObject,h);
 end    
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function pushbutton_1_5_Callback(hObject, eventdata)
% hObject    handle to pushbutton1 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
    % Load the handle structure (h) 
    h = guidata(hObject);
    % Get the selected file 
    File_Selected=get(h.edit_1_1,'String');
    % Get the file extension
    [pathstr, name, ext] = fileparts(File_Selected);
    if ~isempty(pathstr)
        winopen(pathstr);
    end
    % Update the handle structure (h)
    guidata(hObject,h);
 end  
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Tab 2 Export
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Export Panel
h.panel_2_1 = uipanel(h.tab2,...
                    'Title','Export',...
                    'unit','pix',...
                    'Position',[5 435 740 130]);
% Path editbox
h.edit_2_1 = uicontrol('Parent',h.panel_2_1,...
                    'style','edit',...
                    'unit','pix',...
                    'BackgroundColor','white',...
                    'HorizontalAlignment','left',...
                    'Position',[20 70 690 25]);
% Browse Button
h.button_2_1 = uicontrol('Parent',h.panel_2_1,...
                    'Style','pushbutton',...
                    'String','Browse ...',...
                    'Position',[20 20 80 25],...
                    'Callback',@pushbutton_2_1_Callback);
% Load System Button
h.button_2_2 = uicontrol('Parent',h.panel_2_1,...
                    'Style','pushbutton',...
                    'String','Load System',...
                    'Position',[105 20 80 25],...
                    'Callback',@pushbutton_2_2_Callback);
% Start Button
h.button_2_4 = uicontrol('Parent',h.panel_2_1,...
                    'Style','pushbutton',...
                    'String','Start',...
                    'Position',[630 20 80 25],...
                    'Callback',@pushbutton_2_4_Callback);
% Open Folder Button
h.button_2_5 = uicontrol('Parent',h.panel_2_1,...
                    'Style','pushbutton',...
                    'String','Open Folder',...
                    'Position',[190 20 80 25],...
                    'Callback',@pushbutton_2_5_Callback);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Charts - Panel
h.panel_2_2 = uipanel(h.tab2,...
                    'Title','Charts',...
                    'unit','pix',...
                    'Position',[5 305 740 130]);
% Charts - Listbox
h.edit_2_3 = uicontrol('Parent',h.panel_2_2,...   
                    'style','listbox',...
                    'string',{'...'},...
                    'unit','pix',...
                    'BackgroundColor','white',...
                    'HorizontalAlignment','left',...
                    'Position',[20 20 690 85]);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Status - Panel
h.panel_2_3 = uipanel(h.tab2,...
                    'Title','Status',...
                    'unit','pix',...
                    'Position',[5 40 740 265]);
% Status - Textbox
h.edit_2_2 = uicontrol('Parent',h.panel_2_3,...   
                    'style','edit',...
                    'unit','pix',...
                    'Max',2,...
                    'BackgroundColor','white',...
                    'HorizontalAlignment','left',...
                    'Position',[20 70 690 160]);
% get Java handle
j.edit_2_2 = findjobj(h.edit_2_2);
try
    j.editbox_2_2 = j.edit_2_2.getViewport().getComponent(0);
catch
    %try again
    j.editbox_2_2 = j.edit_2_2.getViewport().getComponent(0);
end
% set edit-box to read-only
j.editbox_2_2.setEditable(false);
% turn off word-wrapping
j.editbox_2_2.setWrapping(false);
% enable horizontal scrolling
set(j.edit_2_2,'HorizontalScrollBarPolicy',30);

% Print to Matlab - Button
h.button_2_3 = uicontrol('Parent',h.panel_2_3,...
                    'style','push',...
                    'unit','pix',...
                    'position',[20 20 80 25],...
                    'string','Print to File');
set(h.button_2_3,'callback',@pushbutton_2_3_Callback) % Set callbacks.

% Save the handle structure (h)
MainFigure = h.fig;
guidata(MainFigure,h);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Tab 2 Callback Functions                
function pushbutton_2_1_Callback(hObject, eventdata)
% hObject    handle to pushbutton1 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
    % Load the handle structure (h) 
    h = guidata(hObject);
    % Open the file selection pop up
    [FileName,PathName,FilterIndex] = uigetfile( ...
                    {'*.mdl','Simulink Model (*.mdl)'; ...
                    '*.*',  'All Files (*.*)'}, ...
                    'Select Export-File',h.ExportPathName);
    % This Code executes when a File was selected 
    if FileName>0
        set(h.edit_2_1, 'String', [PathName FileName]);
        % save the Path in guidata for the next invoke of uigetfile 
        h.ExportPathName = PathName;
    end
    % Update the handle structure (h)
    guidata(hObject,h);
 end    
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function pushbutton_2_2_Callback(hObject, eventdata)
% hObject    handle to pushbutton2 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
    % Load the handle structure (h) 
    h = guidata(hObject);  

    % Get the selected file 
    File_Selected=get(h.edit_2_1,'String');
    % Get the file extension
    [pathstr, name, ext] = fileparts(File_Selected);
    % proof if an .mdl File is selected
    if strcmp(ext,'.mdl')
        % open the selected System
        load_system(File_Selected);
        % find all Subsystems that are not masked
        ChartString=find_system(name,'LookUnderMasks','none','blocktype', 'SubSystem');
        % deleting the first 2 positions of the Array
%         if length(ChartString) > 2
%             ChartString([1 2])=[];
%         end
        % write the array to the ListBox
        set(h.edit_2_3,'String',ChartString);
    end
    % Update the handle structure (h) 
    guidata(hObject,h);
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [] = pushbutton_2_3_Callback(hObject, eventdata)
    % callback for pushbutton
    
    % Load the handle structure (h) 
    h = guidata(hObject);  
    file = fopen(['Status_Files\' datestr(now, 'yy-mm-dd_-_HH-MM') '_EXPORT_STATUS.txt'],'w');
    %print cell array to file
    Text = get(h.edit_2_2,'string');     
    for i=1:length(Text)
        fprintf(file,'%s\n',Text{i});
    end    
    fclose(file);
    
    % Update the handle structure (h) 
    guidata(hObject,h);
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [] = pushbutton_2_4_Callback(hObject, eventdata)
    % callback for pushbutton
    % Load the handle structure (h) 
    h = guidata(hObject); 
    % Get the selected file 
    File_Selected=get(h.edit_2_1,'String');
    % Get the file extension
    [FilePath,FileName, ext] = fileparts(File_Selected);
    % proof if an .mdl File is selected
    if strcmp(ext,'.mdl')
        % create Folder for the Result
        NewFilePath = [FilePath '\' FileName];
        % if Folder doesn't exist
        if ~(exist(NewFilePath) == 7)
            % create the Folder
            mkdir(NewFilePath); 
        end
        % get the selected Chart
        system = get(h.edit_2_3,{'string','value'});
        system = system{1}{system{2}};
        xmlFile = system;
        % transform the ChartAdress to the xmlFile Name
        xmlFile(max(find(xmlFile=='/')))='@';
        xmlFile(max(find(xmlFile=='/')))=char(39);
        xmlFile=['Chart_' xmlFile '.xml'];
        xmlFile=[NewFilePath '\' xmlFile];
        % Writing to Status Textbox
        set(h.edit_2_2, 'String', {[' === Status Report (' datestr(now) ') ===']; ''})
        % run the ExportXML Function
        [Errors] = ExportXML (xmlFile, system, h, FirmwareLib);
    end
    % Update the handle structure (h) 
    guidata(hObject,h);
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function pushbutton_2_5_Callback(hObject, eventdata)
% hObject    handle to pushbutton1 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
    % Load the handle structure (h) 
    h = guidata(hObject);
    % Get the selected file
    File_Selected=get(h.edit_2_1,'String');
    % Get the file extension
    [pathstr, name, ext] = fileparts(File_Selected);
    if ~isempty(pathstr)
        winopen(pathstr);
    end
    % Update the handle structure (h)
    guidata(hObject,h);
 end  
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Tab 3 SCL2C
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Matlab Path - Panel
h.panel_3_1 = uipanel(h.tab3,...
                    'Title','Functionblock Path',...
                    'unit','pix',...
                    'Position',[5 435 740 130]);

                
                
% Path editbox
h.edit_3_1 = uicontrol('Parent',h.panel_3_1,...
                    'style','edit',...
                    'unit','pix',...
                    'BackgroundColor','white',...
                    'HorizontalAlignment','left',...
                    'Position',[20 70 690 25], ...
                    'Enable', 'off');
                
% Browse Button
h.button_3_1 = uicontrol('Parent',h.panel_3_1,...
                    'Style','pushbutton',...
                    'String','Browse ...',...
                    'Position',[20 20 80 25],...
                    'Callback',@pushbutton_3_1_Callback);
                
% Translate Button
h.button_3_2 = uicontrol('Parent',h.panel_3_1,...
                    'Style','pushbutton',...
                    'String','Translate ...',...
                    'Position',[105 20 80 25],...
                    'Enable', 'off',...                    
                    'Callback',@pushbutton_3_2_Callback);
                
% % Compile Button
h.button_3_3 = uicontrol('Parent',h.panel_3_1,...
                    'Style','pushbutton',...
                    'String','Compile ...',...
                    'Position',[190 20 80 25],...
                    'Enable', 'off',...
                    'Callback',@pushbutton_3_3_Callback);
                
                
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Charts - Panel
h.panel_3_4 = uipanel(h.tab3,...
                    'Title','SCL Files',...
                    'unit','pix',...
                    'Position',[5 305 740 130]);
% Charts - Listbox
h.edit_3_5 = uicontrol('Parent',h.panel_3_4,...   
                    'style','listbox',...
                    'string',{'...'},...
                    'unit','pix',...
                    'BackgroundColor','white',...
                    'HorizontalAlignment','left',...
                    'Position',[20 20 690 85],...
                    'Callback', @editListbox_3_5_Callback);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Status - Panel
h.panel_3_3 = uipanel(h.tab3,...
                    'Title','Status',...
                    'unit','pix',...
                    'Position',[5 40 740 265]);
% Status - Textbox
h.edit_3_2 = uicontrol('Parent',h.panel_3_3,...   
                    'style','edit',...
                    'unit','pix',...
                    'Max',2,...
                    'BackgroundColor','white',...
                    'HorizontalAlignment','left',...
                    'Position',[20 70 690 160]);
                
% % get Java handle
% j.edit_3_2 = findjobj(h.edit_3_2);
% j.editbox_3_2 = j.edit_3_2.getViewport();
% j.editbox_3_2 = j.editbox_3_2.getComponent(0);
% % set edit-box to read-only
% j.editbox_3_2.setEditable(false);
% % turn off word-wrapping
% j.editbox_3_2.setWrapping(false);
% % enable horizontal scrolling
% set(j.edit_3_2,'HorizontalScrollBarPolicy',30);

% Print to File - Button
h.button_3_4 = uicontrol('Parent',h.panel_3_3,...
                    'style','push',...
                    'unit','pix',...
                    'position',[20 20 80 25],...
                    'string','Print to File');
set(h.button_3_4,'Enable', 'off') % Set callbacks.

% Save the handle structure (h)
MainFigure = h.fig;
guidata(MainFigure,h);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Tab 3 Callback Functions                
function pushbutton_3_1_Callback(hObject, eventdata)
% hObject    handle to pushbutton1 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
    % Load the handle structure (h) 
    h = guidata(hObject);
    % Open the file selection pop up
    dname = uigetdir( 'Select Matlab Path',h.MatlabPathName);
    % This Code executes when a File was selected 
    if dname>0
        set(h.edit_3_1, 'String', dname);
        % save the Path in guidata for the next invoke of uigetfile 
        h.h.MatlabPathName = dname;
    end
    % Update the handle structure (h)
    
    set(h.button_3_2, 'Enable', 'off');
    set(h.button_3_3, 'Enable', 'off');
    set(h.edit_3_5,'value', 1)
    guidata(hObject,h);
    
    list = dir (dname);
    y = 1;
    for i = 1:length(list)
        if ((list(i).isdir == 1) && strcmp(list(i).name(1), '.') ~= 1 && strcmp(list(i).name(1), '..') ~= 1 )
            dir_list{y} = list(i).name;
            
            if (strcmp(list(i).name, 'BASimulation') == 1)
                scl_list(y) = 0;
            else
                D = dir ([dname '\' list(i).name '\source\*.scl' ]);
                scl_list(y) = ~isempty(D);
            end
            
            D = dir ([dname '\' list(i).name '\simulation\!build\*.m' ]);
            build_list(y) = ~isempty(D);
            
            y = y + 1;
        end
    end
    set(h.edit_3_5,'string',dir_list);
    set(h.edit_3_5,'Enable', 'on');
    guidata(hObject,h);
 end    
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% Tab 3 Callback Functions
function editListbox_3_5_Callback(hObject, eventdat)
% hObject    handle to pushbutton1 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
    h = guidata(hObject);
    val = get(h.edit_3_5, 'Value');
    
    if (scl_list(val) == 1)
        set(h.button_3_2, 'Enable', 'on');
    else
        set(h.button_3_2, 'Enable', 'off');
    end
    
    if (build_list(val) == 1)
        set(h.button_3_3, 'Enable', 'on');
    else
        set(h.button_3_3, 'Enable', 'off');
    end
    guidata(hObject,h);
end    
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        

%% Tab 3 Callback Functions Translate Pushbutton             
function pushbutton_3_2_Callback(hObject, eventdata)
% hObject    handle to pushbutton1 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
    h = guidata(hObject);
    
    val = get(h.edit_3_5, 'Value');
    list = get(h.edit_3_5, 'string');
    
    set(h.edit_3_2, 'string', {['Functionblock ' list{val}];...
                                '  Translating...'});
                            
    dname = get(h.edit_3_1, 'String');
    dname = [dname  '\' list{val} '\source\' ];
                            
    SCL2CMasterBatchMatlab(list{val}, dname);
                            
    set(h.edit_3_2, 'string', {['Functionblock ' list{val}];...
                                '  Translating...';...
                                '  Finished';...
                                '';...
                                'Please see the result in the Matlab Command Window'});                                
                            
    guidata(hObject,h);
end    
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% Tab 3 Callback Functions Compile Pushbutton         
function pushbutton_3_3_Callback(hObject, eventdata)
% hObject    handle to pushbutton1 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
    h = guidata(hObject);
    val = get(h.edit_3_5, 'Value');
    list = get(h.edit_3_5, 'string');
    
    dname = get(h.edit_3_1, 'String');

    mfile = [dname '\' list{val} '\simulation\!Build'];
    w = what (mfile);    
    mfile = [mfile '\' w.m{1}];
    
    set(h.edit_3_2, 'string', {['Functionblock ' list{val}];...
                                '  Compiling...'});
    run (mfile);
    
    set(h.edit_3_2, 'string', {['Functionblock ' list{val}];...
                                '  Compiling...';...
                                '  Finished';...
                                '';...
                                'Please see the compile result in the Matlab Command Window'});    
    
    
    guidata(hObject,h);
end    
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Tab 4 Info/Settings
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% FirmwareLib Panel
h.panel_4_1 = uipanel(h.tab4,...
                    'Title','FirmwareLib',...
                    'unit','pix',...
                    'Position',[5 435 740 130]);
% Path editbox
h.text_4_1 = uicontrol('Parent',h.panel_4_1,...
                    'style','text',...
                    'unit','pix',...
                    'string',h.LibFile,...
                    'HorizontalAlignment','left',...
                    'Position',[20 70 690 25]);
% set Lib Button
h.button_4_1 = uicontrol('Parent',h.panel_4_1,...
                    'Style','pushbutton',...
                    'String','set Lib',...
                    'Position',[20 20 80 25],...
                    'Callback',@pushbutton_4_1_Callback);       
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Status - Panel
h.panel_4_2 = uipanel(h.tab4,...
                    'Title','Info',...
                    'unit','pix',...
                    'Position',[5 40 740 395]);
% Info - Textbox
h.text_4_2 = uicontrol('Parent',h.panel_4_2,...   
                    'style','text',...
                    'unit','pix',...
                    'Max',2,...
                    'HorizontalAlignment','left',...
                    'Position',[20 70 690 290]);
% Info String
set(h.text_4_2,'string',...
   {'(C) Copyright by Siemens Schweiz AG, Building Technologies Group,';...
    'HVAC Products, 2012';...
    '';...
    'Project                     : IMSES';...
    'Target Hardware             : PC';...
    'Target Operating System     : WinXP Console';...
    'Language/Compiler           : Matlab 2010 and higher';...
    '';...
    'Workfile                    : GUI.m';...
    'Author                      : Thomas Rohr';...
    'Version                     : v1.1';...
    'Date                        : 20-Feb-2012';...
    ''});
% Save the handle structure (h)
MainFigure = h.fig;
guidata(MainFigure,h);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Tab 4 Callback Functions                
function pushbutton_4_1_Callback(hObject, eventdata)
% hObject    handle to pushbutton1 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
    % Load the handle structure (h) 
    h = guidata(hObject);
    % Open the file selection pop up
    [FileName,PathName,FilterIndex] = uigetfile( ...
                    {'*.mdl','Library-File (*.mdl)'; ...
                    '*.*',  'All Files (*.*)'}, ...
                    'Select Library-File',h.LibFilePathName);
    % This Code executes when a File was selected 
    if FileName>0
        set(h.text_4_1, 'String', [PathName FileName]);
        % save the Path in guidata for the next invoke of uigetfile 
        h.LibFilePathName = PathName;
        % Changing the FirmwareLib Attribute
        % XPath Factory
        import javax.xml.xpath.*
        factory = XPathFactory.newInstance;
        xpath = factory.newXPath;
        % finding the FirmwareLib Node
        expr=xpath.compile('.//FirmwareLib');
        result=expr.evaluate(h.xDocLogFile, XPathConstants.NODE);
        % change the Attribute 
        result.setAttribute('Value',[PathName FileName])
        % writing the DOM xDocLogFile to the XML-File LogFileLocal
        %xmlwrite(h.LogFileLocal,result); % This is not working
        % It creates extra whitespace after every call
        % This is a workaround to solve the whitespace problem
        %LogFile as string
        LogFileStr = xmlwrite(h.xDocLogFile);
        %remove extra tabs, spaces and extra lines
        LogFileStr = regexprep(LogFileStr,'\n[ \t\n]*\n','\n'); 
        %Write to file
        LogFilehandle = fopen(h.LogFileLocal,'w');
        fprintf(LogFilehandle,'%s\n',LogFileStr);
        fclose(LogFilehandle);
    end
    % Update the handle structure (h)
    guidata(hObject,h);
 end   

end