# Generated by Django 4.1.3 on 2022-12-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
