# Generated by Django 4.1.1 on 2022-09-28 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lowlevelcompetence',
            old_name='midlevelkompetenz',
            new_name='parentCompetence',
        ),
    ]
