# Generated by Django 4.1.3 on 2022-12-16 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_competence_slug_alter_ressource_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ressource',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='ressource',
            name='teacher',
        ),
    ]
