# Generated by Django 4.1.1 on 2022-09-28 12:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_competence_competencelevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('createdAt', models.DateTimeField(editable=False)),
            ],
            options={
                'verbose_name_plural': 'Ressources',
            },
        ),
        migrations.AddField(
            model_name='competence',
            name='ressources',
            field=models.ManyToManyField(blank=True, to='main.ressource'),
        ),
    ]
