# Generated by Django 4.1.3 on 2022-12-16 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_ressource_slug_remove_ressource_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AvailableCompetence',
        ),
    ]
