# Generated by Django 4.1.2 on 2022-10-31 10:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_ressource_competence_ressources'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievedCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('createdAt', models.DateTimeField(editable=False)),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.competence')),
            ],
            options={
                'verbose_name_plural': 'Achieved Competences',
            },
        ),
        migrations.CreateModel(
            name='CompetenceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('createdAt', models.DateTimeField(editable=False)),
                ('achievedCompetences', models.ManyToManyField(blank=True, to='main.achievedcompetence')),
                ('competences', models.ManyToManyField(blank=True, to='main.competence')),
            ],
            options={
                'verbose_name_plural': 'Competence Profiles',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('createdAt', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('createdAt', models.DateTimeField(editable=False)),
                ('competenceProfile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.competenceprofile')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.job')),
            ],
            options={
                'verbose_name_plural': 'Teachers',
            },
        ),
        migrations.CreateModel(
            name='PlannedCompetences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plannedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('createdAt', models.DateTimeField(editable=False)),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.competence')),
            ],
            options={
                'verbose_name_plural': 'Planned Competences',
            },
        ),
        migrations.AddField(
            model_name='competenceprofile',
            name='plannedCompetences',
            field=models.ManyToManyField(blank=True, to='main.plannedcompetences'),
        ),
        migrations.AddField(
            model_name='competence',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.job'),
        ),
    ]
