# Generated by Django 4.1.2 on 2022-10-31 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_teacher_competenceprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competenceprofile',
            name='competences',
            field=models.ManyToManyField(blank=True, editable=False, to='main.competence'),
        ),
    ]
