# Generated by Django 4.1.2 on 2022-10-31 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_competenceprofile_competences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competenceprofile',
            name='competences',
            field=models.ManyToManyField(blank=True, to='main.competence'),
        ),
    ]
