# Generated by Django 4.1.2 on 2022-10-31 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_competenceprofile_competences'),
    ]

    operations = [
        migrations.AddField(
            model_name='competenceprofile',
            name='availableCompetences',
            field=models.ManyToManyField(blank=True, related_name='availableCompetences', to='main.competence'),
        ),
        migrations.AlterField(
            model_name='competenceprofile',
            name='competences',
            field=models.ManyToManyField(blank=True, editable=False, to='main.competence'),
        ),
    ]
