# Generated by Django 4.1.1 on 2022-11-03 13:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_competenceprofile_availablecompetences_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competenceprofile',
            name='achievedCompetences',
        ),
        migrations.RemoveField(
            model_name='competenceprofile',
            name='competences',
        ),
        migrations.RemoveField(
            model_name='competenceprofile',
            name='plannedCompetences',
        ),
        migrations.AddField(
            model_name='achievedcompetence',
            name='competenceProfile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.competenceprofile'),
        ),
        migrations.AddField(
            model_name='plannedcompetences',
            name='competenceProfile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.competenceprofile'),
        ),
        migrations.CreateModel(
            name='AvailableCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('createdAt', models.DateTimeField(editable=False)),
                ('CompetenceProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.competenceprofile')),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.competence')),
            ],
            options={
                'verbose_name_plural': 'Avilable Competences',
            },
        ),
    ]
