# Generated by Django 4.1.1 on 2022-11-03 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_competenceprofile_achievedcompetences_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='competenceCategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.competencecategory'),
        ),
    ]
