# Generated by Django 4.1.3 on 2022-12-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_invitecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitecode',
            name='code',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
