# Generated by Django 4.1.3 on 2022-12-13 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_achievedcompetence_slug_plannedcompetences_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievedcompetence',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='plannedcompetences',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
