# Generated by Django 4.1.1 on 2022-09-28 08:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_midlevelkompetenz_lowlevelcompetence_parentcompetence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lowlevelcompetence',
            name='updatedAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='midlevelcompetence',
            name='updatedAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
