# Generated by Django 4.1.1 on 2022-09-28 08:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_lowlevelcompetence_updatedat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toplevelcompetence',
            name='updatedAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
