# Generated by Django 4.1.1 on 2022-09-28 10:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_toplevelcompetence_updatedat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('createdAt', models.DateTimeField(editable=False)),
            ],
            options={
                'verbose_name_plural': 'Competences',
            },
        ),
        migrations.CreateModel(
            name='CompetenceLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('createdAt', models.DateTimeField(editable=False)),
            ],
            options={
                'verbose_name_plural': 'Competence Levels',
            },
        ),
        migrations.RemoveField(
            model_name='midlevelcompetence',
            name='parentCompetence',
        ),
        migrations.AlterModelOptions(
            name='competencecategory',
            options={'verbose_name_plural': 'Competence Categories'},
        ),
        migrations.RenameModel(
            old_name='TopLevelCompetence',
            new_name='CompetenceCategory',
        ),
        migrations.DeleteModel(
            name='LowLevelCompetence',
        ),
        migrations.DeleteModel(
            name='MidLevelCompetence',
        ),
        migrations.AddField(
            model_name='competence',
            name='competenceCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.competencecategory'),
        ),
        migrations.AddField(
            model_name='competence',
            name='competenceLevel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.competencelevel'),
        ),
    ]
