# Generated by Django 4.0.4 on 2022-06-17 12:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_tutorial_tutorialpublished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorialPublished',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 14, 57, 52, 413680), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorialSeries',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.tutorialseries', verbose_name='Series'),
        ),
        migrations.AlterField(
            model_name='tutorialseries',
            name='tutorialCategory',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.tutorialcategory', verbose_name='Category'),
        ),
    ]
