# Generated by Django 4.0.4 on 2022-06-17 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_tutorial_tutorialpublished_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorialPublished',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 16, 38, 32, 790292), verbose_name='date published'),
        ),
    ]
