# Generated by Django 4.0.4 on 2022-06-17 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_tutorial_tutorialpublished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorialPublished',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 21, 52, 46, 96288), verbose_name='date published'),
        ),
    ]
